// Products

export const LOAD_PRODUCTS = 'LOAD_PRODUCTS'
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS'
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR'
export const LOAD_SELECTED_PRODUCT = 'LOAD_SELECTED_PRODUCT'
export const LOAD_SELECTED_PRODUCT_SUCCESS = 'LOAD_SELECTED_PRODUCT_SUCCESS'
export const LOAD_SELECTED_PRODUCT_ERROR = 'LOAD_SELECTED_PRODUCT_ERROR'
export const LOAD_RECOMMENDED_PRODUCTS = 'LOAD_RECOMMENDED_PRODUCTS'
export const LOAD_RECOMMENDED_PRODUCTS_SUCCESS = 'LOAD_RECOMMENDED_PRODUCTS_SUCCESS'
export const LOAD_RECOMMENDED_PRODUCTS_ERROR = 'LOAD_RECOMMENDED_PRODUCTS_ERROR'
export const SET_FILTER_URL = 'SET_FILTER_URL'
export const SET_SORTING_URL = 'SET_SORTING_URL'

// Basket

export const LOAD_BASKET = 'LOAD_BASKET'
export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET'
export const REMOVE_PRODUCT_FROM_BASKET = 'REMOVE_PRODUCT_TO_BASKET'
export const INCREASE_PRODUCT_SELECTED_AMOUNT = 'INCREASE_PRODUCT_SELECTED_AMOUNT'
export const DECREASE_PRODUCT_SELECTED_AMOUNT = 'DECREASE_PRODUCT_SELECTED_AMOUNT'
export const CLEAR_BASKET = 'CLEAR_BASKET'

//Comments

export const LOAD_PRODUCT_COMMENTS = 'LOAD_PRODUCT_COMMENTS'
export const ADD_PRODUCT_COMMENT = 'ADD_PRODUCT_COMMENT'

// User

export const LOAD_USER = 'LOAD_USER'
export const ADD_PRODUCT_TO_WISH_LIST = 'ADD_PRODUCT_TO_WISH_LIST'
export const ADD_PRODUCT_TO_VIEWED_PRODUCTS_LIST = 'ADD_PRODUCT_TO_VIEWED_PRODUCTS_LIST'
export const REMOVE_PRODUCT_FROM_WISH_LIST = 'REMOVE_PRODUCT_FROM_WISH_LIST'
export const MAKE_ORDER = 'MAKE_ORDER'

//Pagination

export const LOAD_MORE = 'LOAD_MORE'

//Search

export const GET_SEARCH_DATA = 'GET_SEARCH_DATA'
export const GET_SEARCH_DATA_SUCCESS = 'GET_SEARCH_DATA_SUCCES'
export const GET_SEARCH_DATA_ERROR = 'GET_SEARCH_DATA_ERROR'

//Top sales

export const LOAD_TOP_SALES = 'LOAD_TOP_SALES'
export const LOAD_TOP_SALES_SUCCESS = 'LOAD_TOP_SALES_SUCCESS'
export const LOAD_TOP_SALES_ERROR = 'LOAD_TOP_SALES_ERROR'

//Auth

export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR'
